const noteEmoji: Record<string, string> = {
  'Canela': '🥢',
  'Lavanda': '🪻',
  'Mandarina': '🍊',
  'Íris': '🌸',
  'Benjoim': '🟤',
  'Cipreste': '🌲',
  'Mahonial': '🌼',
  'Baunilha': '🌿',
  'Fava tonka': '🫘',
  'Âmbar': '🟠',
  'Cedro': '🪵',
  'Incenso': '💨',
  'Patchouli': '🍃',
  'Pimenta rosa': '🌶️',
  'Mirra': '🟤',
  'Cacau': '🍫',
  'Noz-moscada': '🟤',
  'Davana': '🌿',
  'Baunilha bourbon': '🌿',
  'Vetiver': '🌾',
  'Bergamota': '🍋',
  'Tâmara': '🌰',
  'Pralinê': '🍬',
  'Tuberosa': '🤍',
  'Madeiras doces': '🪵',
  'Açafrão': '🧡',
  'Jasmim': '🌼',
  'Âmbar cinza': '⚪',
  'Madeira âmbar': '🪵',
  'Resina de abeto': '🌲',
  'Caramelo': '🍮',
  'Leite': '🥛',
  'Açúcar': '▫️',
  'Mel': '🍯',
  'Flores brancas': '🤍',
  'Almíscar': '⚪',
  'Cítricos': '🍋',
  'Notas verdes': '🌿',
  'Rosa': '🌹',
  'Oud suave': '🪵',
  'Madeira seca': '🪵',
  'Gengibre': '🫚',
  'Cardamomo': '🟢',
  'Coco': '🥥',
  'Abacaxi': '🍍',
  'Morango': '🍓',
  'Champagne': '🥂',
  'Chocolate': '🍫',
  'Marshmallow': '☁️',
  'Kiwi': '🥝',
  'Lichia vermelha': '🍒',
  'Marmelo': '🍐',
  'Chocolate branco': '🍫',
  'Couro': '🤎',
  'Sândalo': '🪵',
  'Pimenta preta': '⚫',
  'Lavanda marinha': '💜',
  'Água de coco': '🥥',
  'Sal': '🧂',
  'Amêndoa amarga': '🌰',
  'Damasco': '🍑',
  'Ruibarbo': '🌱',
  'Ládano': '🟤',
  'Notas marinhas': '🌊',
  'Limão siciliano': '🍋',
  'Musgo de carvalho': '🌿',
  'Ameixa': '🟣',
  'Maçã': '🍎',
  'Lichia': '🍒',
  'Crème brûlée': '🍮',
  'Cúrcuma': '🟡',
  'Cashmeran': '🪶',
  'Bálsamo de abeto': '🌲',
  'Laranja sanguínea': '🍊',
  'Gardênia': '🌼',
  'Orquídea baunilha': '🌺',
  'Castanha': '🌰',
  'Lírio': '🌼',
  'Aldeídos': '✨',
  'Madressilva': '🌼',
  'Ylang-ylang': '🌼',
  'Flor de laranjeira': '🌼',
  'Almíscar branco': '⚪',
};

export function NoteIcon({ note }: { note: string }) {
  return (
    <div className="flex h-full w-full items-center justify-center rounded-2xl bg-white text-4xl">
      {noteEmoji[note] ?? '✦'}
    </div>
  );
}
